version: '3.8'
services:
   web:
      build: .
      command: python /code/manage.py runserver 0.0.0.0:8000
      volumes:
         - .:/code
      ports:
         - 8000:800
      depends_on: 
         - db

   db:
      image: postgres:12
      environment:
         POSTGRES_DB: "db"
         POSTGRES_HOST_AUTH_METHOD: "trust"
      volumes:
         - postgres_data:/var/lib/postgresql/data/

volumes: 
   postgres_data: